# Generated by Django 4.2.3 on 2023-07-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('prompt_type', models.CharField(max_length=240, verbose_name='Type')),
                ('tags', models.CharField(max_length=240, verbose_name='Tags')),
                ('audio_file', models.CharField(max_length=240, verbose_name='Audio file')),
                ('duration', models.CharField(max_length=240, verbose_name='Duration')),
            ],
        ),
    ]
