# Generated by Django 4.2.3 on 2023-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0002_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('tag', models.CharField(max_length=240, verbose_name='Matches tag')),
                ('icon', models.FileField(upload_to='prompt_group_icons', verbose_name='Icon file')),
                ('position', models.FloatField(verbose_name='List position')),
                ('is_active', models.BooleanField(verbose_name='Active')),
            ],
        ),
        migrations.AlterField(
            model_name='prompt',
            name='audio_file',
            field=models.FileField(upload_to='prompt_audio', verbose_name='Audio file'),
        ),
    ]
