# Generated by Django 4.2.3 on 2023-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0003_promptgroup_alter_prompt_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='promptgroup',
            name='title',
        ),
        migrations.AddField(
            model_name='promptgroup',
            name='name',
            field=models.CharField(default='group', max_length=240, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promptgroup',
            name='icon',
            field=models.FileField(blank=True, upload_to='prompt_group_icons', verbose_name='Icon file'),
        ),
    ]
