# Generated by Django 4.2.3 on 2023-08-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0004_remove_prompt_duration_remove_promptgroup_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='intro_audio_file',
            field=models.FileField(blank=True, upload_to='prompt_audio', verbose_name='Intro audio file'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ScenarioPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(verbose_name='List position')),
                ('trigger', models.CharField(max_length=240, verbose_name='Trigger type')),
                ('delay', models.IntegerField(verbose_name='Delay (seconds)')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converse.prompt')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converse.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='scenario',
            name='prompts',
            field=models.ManyToManyField(through='converse.ScenarioPrompt', to='converse.prompt'),
        ),
    ]
